name: 'SAM Deployment'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: 'SAM Deployment'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

    # Deploy SAM Stack when pushing to master
    - name: AWS SAM Deploy
      #if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      # Make sure you are in the SAM-APP directory before running the build
      run: |
        sam build
        sam deploy
